# ====================================================
# Background information
# ====================================================

# Prescribe background information
GammaT = 0.0065 # Temperature lapse rate, unit: K/m
T0     = 300.0  # Surface temperature, unit: K
p0     = 100000.0 # Surface temperature, unit: Pa