# ====================================================
# Setting for domain size, interval, etc.
# ====================================================

[Domain]
# Setting in physical space
T = 30.0       # Total time of simulation, unit: day
X = 40000000.0 # Maximum size of horizontal domain, unit: m
Z = 14000.0    # The upper boundary of vertical domain, unit: m
Ens = 10       # Ensemble size

dt = 0.5      # Time step, unit: day
dx = 50000.0   # horizontal spacing, unit: m
dz = 200.0     # vertical spacing, unit: m

# Setting in wavenumber space
kmin = 0.0679  # minimum wavenumber sampling, corresponding to lambda = 399754 km, unit: 1/m
kmax = 20.358 # maximum wavenumber sampling, corresponding to lambda = 1333 km, unit: 1/m
dk   = 0.4     # interval in wavenumber space, unit: 1/m