# ====================================================
# Scaling for different state vector
# ====================================================

[Init]
w1scale = 1.0 # scaling on vertical motion, defualt: 100
w2scale = 1.0
T1scale = 1.0  # scaling on temperature, default: 10
T2scale = 1.0
qscale  = 1   # scaling on moisture, default: 0.1
Lscale  = 1.0 # scaling on convective heating, default: 100
